[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.13.0",
    "asyncpg>=0.29.0",
    "azure-storage-blob>=12.26.0",
    "boto3>=1.40.32",
    "celery[redis]>=5.3.1",
    "colorlog>=6.9.0",
    "faker>=37.8.0",
    "fastapi-mail>=1.5.0",
    "fastapi[standard]>=0.116.2",
    "flower>=2.0.1",
    "greenlet>=3.2.4",
    "httpx>=0.28.1",
    "langchain>=0.3.27",
    "langchain-ollama>=0.3.8",
    "langchain-openai>=0.3.33",
    "passlib>=1.7.4",
    "psycopg2-binary>=2.9.9",
    "punq>=0.7.0",
    "pydantic>=2.11.9",
    "pydantic-settings>=2.10.1",
    "pyjwt>=2.10.1",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "python-dotenv>=1.1.1",
    "redis>=6.4.0",
    "sqlalchemy>=2.0.23",
    "sqlmodel>=0.0.14",
    "starlette>=0.48.0",
    "webauthn>=2.7.0",
]
